[package]
name = "cuckoo"
version = "0.1.0"
authors = ["James Lao <lao.james@gmail.com>"]

[dependencies]
rand = "0.5.5"

[dev-dependencies]
criterion = "0.2"

[lib]
bench = false

[[bench]]
name = "hashmap"
harness = false